import { createHash, timingSafeEqual } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { pgProtectedProcedure as pgTenantProcedure, router } from "../_core/trpc";
import { withTenantBranchTransaction } from "../db.pg";
import { evidenceStorageProvider, localEvidenceStorage } from "../evidenceStorage";

const uuid = z.string().uuid();
const context = z.object({ branchId: uuid, tenantId: uuid.optional() });
const maxBytes = Number(process.env.HOROS_EVIDENCE_MAX_BYTES || 20 * 1024 * 1024);
const types = z.enum(["PHOTO", "DOCUMENT", "SCREENSHOT", "LOG_EXPORT", "TEST_RESULT", "OTHER"]);
const allowed = new Set(["image/jpeg", "image/png", "image/webp", "application/pdf", "text/plain", "text/csv"]);
function fail(code: "BAD_REQUEST"|"NOT_FOUND"|"FORBIDDEN"|"CONFLICT", message:string):never { throw new TRPCError({code,message}); }
function manage(role:string){if(!["admin","technician"].includes(role))fail("FORBIDDEN","Evidence management permission is required");}
const pgProtectedProcedure=pgTenantProcedure.use(async({ctx,next})=>{manage(ctx.pgTenant.tenantRole);return next({ctx});});
function decode(value:string) { if(!value||value.length>Math.ceil(maxBytes*4/3)+8||!/^[A-Za-z0-9+/]*={0,2}$/.test(value)) fail("BAD_REQUEST","Evidence payload is invalid or exceeds the configured limit"); const bytes=Buffer.from(value,"base64"); if(!bytes.length||bytes.length>maxBytes) fail("BAD_REQUEST","Evidence file must be non-empty and within the configured limit"); return bytes; }
function detect(bytes:Buffer):string { if(bytes.subarray(0,3).equals(Buffer.from([255,216,255])))return"image/jpeg";if(bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))return"image/png";if(bytes.length>=12&&bytes.toString("ascii",0,4)==="RIFF"&&bytes.toString("ascii",8,12)==="WEBP")return"image/webp";if(bytes.subarray(0,5).toString("ascii")==="%PDF-")return"application/pdf";const sample=bytes.subarray(0,Math.min(bytes.length,4096));if(sample.includes(0))return"application/octet-stream";const text=sample.toString("utf8").trimStart().toLowerCase();if(text.startsWith("<svg")||text.startsWith("<!doctype html")||text.startsWith("<html")||text.includes("<script"))return"text/html";return text.includes(",")&&text.includes("\n")?"text/csv":"text/plain"; }
function extensionMatches(name:string,mime:string){const ext=name.toLowerCase().split(".").pop();return({"image/jpeg":["jpg","jpeg"],"image/png":["png"],"image/webp":["webp"],"application/pdf":["pdf"],"text/plain":["txt","log"],"text/csv":["csv"]}as Record<string,string[]>)[mime]?.includes(ext||"")??false;}
const sha=(bytes:Buffer)=>createHash("sha256").update(bytes).digest("hex");
const safeName=(name:string)=>name.replace(/[\r\n"\\/]/g,"_").slice(0,255)||"evidence";
const inBranch=<T>(ctx:{pgTenant:{tenantId:string}},branchId:string,callback:Parameters<typeof withTenantBranchTransaction<T>>[2])=>withTenantBranchTransaction(ctx.pgTenant.tenantId,branchId,callback);
async function actor(tx:any,tenantId:string,subject:string){const rows=await tx`SELECT u.id::text id FROM users u JOIN tenant_users tu ON tu.user_id=u.id AND tu.tenant_id=${tenantId}::uuid AND tu.is_active WHERE u.external_subject=${subject} AND u.is_active LIMIT 1`;if(rows.length!==1)fail("FORBIDDEN","Active canonical membership is required");return rows[0].id as string;}
async function event(tx:any,tenantId:string,branchId:string,id:string,type:string,subject:string,details:object={}){await tx`INSERT INTO evidence_events(tenant_id,branch_id,evidence_id,event_type,actor_external_subject,details) VALUES(${tenantId}::uuid,${branchId}::uuid,${id}::uuid,${type},${subject},${tx.json(details)})`;}
const publicColumns=`id::text,work_order_id::text AS "workOrderId",finding_id::text AS "findingId",inspection_id::text AS "inspectionId",inspection_result_id::text AS "inspectionResultId",asset_id::text AS "assetId",component_id::text AS "componentId",evidence_type AS "evidenceType",file_name AS "originalFilename",content_type_detected AS "contentType",byte_size::int AS "byteSize",sha256,status,taken_at AS "capturedAt",uploaded_at AS "uploadedAt",uploaded_by_user_id::text AS "uploadedBy",caption AS description,supersedes_evidence_id::text AS "supersedesEvidenceId"`;

export const secureEvidenceRouter=router({
  initiate:pgProtectedProcedure.input(context.extend({workOrderId:uuid.optional(),findingId:uuid.optional(),inspectionId:uuid.optional(),inspectionResultId:uuid.optional(),assetId:uuid.optional(),componentId:uuid.optional(),evidenceType:types,originalFilename:z.string().trim().min(1).max(255),contentTypeDeclared:z.string().max(128),capturedAt:z.coerce.date().optional(),description:z.string().max(5000).optional(),supersedesEvidenceId:uuid.optional()})).mutation(async({ctx,input})=>inBranch(ctx,input.branchId,async tx=>{if(!input.workOrderId&&!input.inspectionId)fail("BAD_REQUEST","Evidence requires a work order or inspection");const uploadedBy=await actor(tx,ctx.pgTenant.tenantId,ctx.pgTenant.externalSubject);const key=localEvidenceStorage.createKey();const rows=await tx`INSERT INTO maintenance_evidence(tenant_id,branch_id,work_order_id,finding_id,inspection_id,inspection_result_id,asset_id,component_id,evidence_type,media_type,file_name,mime_type,storage_provider,storage_key,content_type_declared,status,taken_at,uploaded_at,uploaded_by_user_id,caption,source,supersedes_evidence_id) VALUES(${ctx.pgTenant.tenantId}::uuid,${input.branchId}::uuid,${input.workOrderId??null}::uuid,${input.findingId??null}::uuid,${input.inspectionId??null}::uuid,${input.inspectionResultId??null}::uuid,${input.assetId??null}::uuid,${input.componentId??null}::uuid,${input.evidenceType},${input.evidenceType==='PHOTO'||input.evidenceType==='SCREENSHOT'?'photo':'document'},${safeName(input.originalFilename)},${input.contentTypeDeclared},${evidenceStorageProvider},${key},${input.contentTypeDeclared},'PENDING_UPLOAD',${input.capturedAt??null},now(),${uploadedBy}::uuid,${input.description??null},'DIRECT_UPLOAD',${input.supersedesEvidenceId??null}::uuid) RETURNING id::text`;await event(tx,ctx.pgTenant.tenantId,input.branchId,rows[0].id,'upload_initiated',ctx.pgTenant.externalSubject);return{id:rows[0].id,status:'PENDING_UPLOAD' as const};})),
  upload:pgProtectedProcedure.input(context.extend({id:uuid,fileBase64:z.string().min(1),clientSha256:z.string().optional(),clientByteSize:z.number().optional()})).mutation(async({ctx,input})=>{const bytes=decode(input.fileBase64);const detected=detect(bytes);const digest=sha(bytes);const record=await inBranch(ctx,input.branchId,async tx=>{const rows=await tx`SELECT id::text,storage_key AS "storageKey",file_name AS "fileName",content_type_declared AS declared,status FROM maintenance_evidence WHERE id=${input.id}::uuid`;if(rows.length!==1)fail("NOT_FOUND","Evidence was not found");if(rows[0].status!=='PENDING_UPLOAD')fail("CONFLICT","Evidence upload has already been received");return rows[0] as any;});if(!allowed.has(detected)||detected!==record.declared||!extensionMatches(record.fileName,detected)){await inBranch(ctx,input.branchId,async tx=>{await tx`UPDATE maintenance_evidence SET status='REJECTED',content_type_detected=${detected},byte_size=${bytes.length},rejection_reason='File signature, declaration, or extension is not allowed' WHERE id=${input.id}::uuid`;await event(tx,ctx.pgTenant.tenantId,input.branchId,input.id,'file_rejected',ctx.pgTenant.externalSubject);});fail("BAD_REQUEST","File signature, declared type, or extension is not allowed");}try{await localEvidenceStorage.putExclusive(record.storageKey,bytes);}catch{fail("CONFLICT","Private evidence object could not be stored without overwrite");}return inBranch(ctx,input.branchId,async tx=>{await tx`UPDATE maintenance_evidence SET status='PROCESSING',content_type_detected=${detected},byte_size=${bytes.length},sha256=${digest} WHERE id=${input.id}::uuid AND status='PENDING_UPLOAD'`;await event(tx,ctx.pgTenant.tenantId,input.branchId,input.id,'upload_received',ctx.pgTenant.externalSubject,{contentType:detected,byteSize:bytes.length});return{id:input.id,status:'PROCESSING' as const};});}),
  finalize:pgProtectedProcedure.input(context.extend({id:uuid})).mutation(async({ctx,input})=>{const record=await inBranch(ctx,input.branchId,async tx=>{const rows=await tx`SELECT storage_key AS "storageKey",byte_size::int AS "byteSize",sha256,status FROM maintenance_evidence WHERE id=${input.id}::uuid`;if(rows.length!==1)fail("NOT_FOUND","Evidence was not found");return rows[0] as any;});if(record.status==='AVAILABLE')return{id:input.id,status:'AVAILABLE' as const};if(record.status!=='PROCESSING')fail("CONFLICT","Evidence is not ready for verification");const bytes=await localEvidenceStorage.read(record.storageKey);const verified=sha(bytes);if(bytes.length!==record.byteSize||!timingSafeEqual(Buffer.from(verified),Buffer.from(record.sha256)))fail("CONFLICT","Stored evidence integrity verification failed");return inBranch(ctx,input.branchId,async tx=>{const updated=await tx`UPDATE maintenance_evidence SET status='AVAILABLE' WHERE id=${input.id}::uuid AND status='PROCESSING' RETURNING supersedes_evidence_id::text AS "supersedesId"`;const oldId=updated[0]?.supersedesId;if(oldId){await tx`UPDATE maintenance_evidence SET status='SUPERSEDED' WHERE id=${oldId}::uuid AND status='AVAILABLE'`;await event(tx,ctx.pgTenant.tenantId,input.branchId,oldId,'evidence_superseded',ctx.pgTenant.externalSubject,{replacementId:input.id});}await event(tx,ctx.pgTenant.tenantId,input.branchId,input.id,'file_verified',ctx.pgTenant.externalSubject);return{id:input.id,status:'AVAILABLE' as const};});}),
  list:pgProtectedProcedure.input(context.extend({workOrderId:uuid.optional(),findingId:uuid.optional(),inspectionId:uuid.optional(),inspectionResultId:uuid.optional(),assetId:uuid.optional(),componentId:uuid.optional()})).query(({ctx,input})=>inBranch(ctx,input.branchId,tx=>tx.unsafe(`SELECT ${publicColumns} FROM maintenance_evidence WHERE ($1::uuid IS NULL OR work_order_id=$1) AND ($2::uuid IS NULL OR finding_id=$2) AND ($3::uuid IS NULL OR inspection_id=$3) AND ($4::uuid IS NULL OR inspection_result_id=$4) AND ($5::uuid IS NULL OR asset_id=$5) AND ($6::uuid IS NULL OR component_id=$6) ORDER BY uploaded_at DESC`,[input.workOrderId??null,input.findingId??null,input.inspectionId??null,input.inspectionResultId??null,input.assetId??null,input.componentId??null]))),
  metadata:pgProtectedProcedure.input(context.extend({id:uuid})).query(async({ctx,input})=>{const rows=await inBranch(ctx,input.branchId,tx=>tx.unsafe(`SELECT ${publicColumns} FROM maintenance_evidence WHERE id=$1::uuid`,[input.id]));if(!rows.length)fail("NOT_FOUND","Evidence was not found");return rows[0];}),
  updateDescription:pgProtectedProcedure.input(context.extend({id:uuid,description:z.string().max(5000)})).mutation(({ctx,input})=>inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE maintenance_evidence SET caption=${input.description} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)fail("NOT_FOUND","Evidence was not found");await event(tx,ctx.pgTenant.tenantId,input.branchId,input.id,'description_updated',ctx.pgTenant.externalSubject);return{id:input.id};})),
  supersede:pgProtectedProcedure.input(context.extend({id:uuid,replacementId:uuid})).mutation(({ctx,input})=>inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE maintenance_evidence old SET status='SUPERSEDED' WHERE old.id=${input.id}::uuid AND old.status='AVAILABLE' AND EXISTS(SELECT 1 FROM maintenance_evidence newer WHERE newer.id=${input.replacementId}::uuid AND newer.supersedes_evidence_id=old.id AND newer.status='AVAILABLE') RETURNING old.id`;if(!rows.length)fail("BAD_REQUEST","A verified replacement is required");await event(tx,ctx.pgTenant.tenantId,input.branchId,input.id,'evidence_superseded',ctx.pgTenant.externalSubject,{replacementId:input.replacementId});return{id:input.id,status:'SUPERSEDED' as const};})),
  history:pgProtectedProcedure.input(context.extend({id:uuid})).query(({ctx,input})=>inBranch(ctx,input.branchId,tx=>tx`SELECT event_type AS "eventType",actor_external_subject AS actor,details,created_at AS "createdAt" FROM evidence_events WHERE evidence_id=${input.id}::uuid ORDER BY created_at,id`)),
});
