import { randomUUID } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { pgProtectedProcedure, router } from "../_core/trpc";
import { withTenantBranchTransaction } from "../db.pg";

const branchInput = z.object({ branchId: z.string().uuid(), tenantId: z.string().uuid().optional() });
const uuid = z.string().uuid();
const portType = z.enum(["ETHERNET","FIBER","POWER","RELAY_INPUT","RELAY_OUTPUT","ALARM_INPUT","AUDIO_INPUT","AUDIO_OUTPUT","SERIAL","WIRELESS","LOGICAL","OTHER"]);
const direction = z.enum(["INPUT","OUTPUT","BIDIRECTIONAL","NOT_APPLICABLE"]);
const medium = z.enum(["COPPER","FIBER","WIRELESS","ELECTRICAL","AUDIO","LOGICAL","OTHER"]);
const linkType = z.enum(["PHYSICAL","WIRELESS","LOGICAL"]);
const relationshipType = z.enum(["POWERED_BY","CONTROLLED_BY","RECORDED_BY","MONITORED_BY","HOSTED_ON","DEPENDS_ON","SERVES","BACKED_UP_BY","PARENT_OF","CONNECTED_TO","OTHER"]);

function requireAdmin(role: string) { if (role !== "admin") throw new TRPCError({ code: "FORBIDDEN", message: "Administrator permission is required" }); }
function controlled(error: unknown): never {
  if (error instanceof TRPCError) throw error;
  const code = typeof error === "object" && error && "code" in error ? String((error as { code?: unknown }).code) : "";
  if (code === "23505") throw new TRPCError({ code: "CONFLICT", message: "An active topology record already uses this code or endpoint" });
  if (["23503","23514","P0002"].includes(code)) throw new TRPCError({ code: "BAD_REQUEST", message: "Topology context or compatibility is invalid" });
  throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Canonical topology operation failed" });
}
const inBranch = <T>(ctx: { pgTenant: { tenantId: string } }, branchId: string, fn: Parameters<typeof withTenantBranchTransaction<T>>[2]) => withTenantBranchTransaction(ctx.pgTenant.tenantId, branchId, fn);
async function audit(tx: any, tenantId: string, branchId: string, entityType: string, entityId: string, eventType: string, actor: string, details: object = {}) {
  await tx`INSERT INTO asset_topology_events (tenant_id,branch_id,entity_type,entity_id,event_type,actor_external_subject,details) VALUES (${tenantId}::uuid,${branchId}::uuid,${entityType},${entityId}::uuid,${eventType},${actor},${tx.json(details)})`;
}

export const topologyRouter = router({
  context: pgProtectedProcedure.input(branchInput).query(({ ctx, input }) =>
    inBranch(ctx, input.branchId, async tx => ({
      canManage: ctx.pgTenant.tenantRole === "admin",
      assets: await tx`
        SELECT a.id::text, a.asset_code AS "assetCode",
          a.system_solution_id::text AS "systemSolutionId",
          COALESCE(jsonb_agg(jsonb_build_object('value', aa.alias_value, 'type', aa.alias_type))
            FILTER (WHERE aa.id IS NOT NULL), '[]') AS aliases
        FROM assets a
        LEFT JOIN asset_aliases aa ON aa.tenant_id = a.tenant_id
          AND aa.branch_id = a.branch_id AND aa.asset_id = a.id AND aa.active
        WHERE a.branch_id = ${input.branchId}::uuid
        GROUP BY a.id ORDER BY a.asset_code
      `,
    })),
  ),
  listPorts: pgProtectedProcedure.input(branchInput.extend({ assetId: uuid })).query(({ctx,input}) => inBranch(ctx,input.branchId,tx => tx`SELECT id::text,asset_id::text AS "assetId",code,name,port_type AS "portType",direction,medium,connector_type AS "connectorType",status,sequence,description,active FROM asset_ports WHERE asset_id=${input.assetId}::uuid ORDER BY sequence NULLS LAST,code`)),
  listAvailablePorts: pgProtectedProcedure.input(branchInput).query(({ctx,input}) => inBranch(ctx,input.branchId,tx => tx`SELECT p.id::text,p.asset_id::text AS "assetId",a.asset_code AS "assetCode",p.code,p.name,p.medium,p.active,NOT EXISTS(SELECT 1 FROM asset_links l WHERE l.active AND (l.endpoint_a_port_id=p.id OR l.endpoint_b_port_id=p.id)) AS available FROM asset_ports p JOIN assets a ON a.tenant_id=p.tenant_id AND a.branch_id=p.branch_id AND a.id=p.asset_id WHERE p.active ORDER BY a.asset_code,p.code`)),
  getPort: pgProtectedProcedure.input(branchInput.extend({ id: uuid })).query(async ({ctx,input}) => { const rows=await inBranch(ctx,input.branchId,tx=>tx`SELECT * FROM asset_ports WHERE id=${input.id}::uuid`); if(!rows.length) throw new TRPCError({code:"NOT_FOUND",message:"Port was not found"}); return rows[0]; }),
  createPort: pgProtectedProcedure.input(branchInput.extend({ assetId:uuid,code:z.string().trim().min(1).max(64),name:z.string().trim().min(1).max(255),portType,direction,medium,connectorType:z.string().max(64).nullable().optional(),description:z.string().max(5000).nullable().optional() })).mutation(async ({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);try{return await inBranch(ctx,input.branchId,async tx=>{const id=randomUUID();await tx`INSERT INTO asset_ports(id,tenant_id,branch_id,asset_id,code,name,port_type,direction,medium,connector_type,description,created_by,updated_by) VALUES(${id}::uuid,${ctx.pgTenant.tenantId}::uuid,${input.branchId}::uuid,${input.assetId}::uuid,${input.code.toUpperCase()},${input.name},${input.portType},${input.direction},${input.medium},${input.connectorType??null},${input.description??null},${ctx.pgTenant.externalSubject},${ctx.pgTenant.externalSubject})`;await audit(tx,ctx.pgTenant.tenantId,input.branchId,"PORT",id,"port_created",ctx.pgTenant.externalSubject);return {id};});}catch(e){controlled(e);}}),
  updatePort: pgProtectedProcedure.input(branchInput.extend({id:uuid,name:z.string().trim().min(1).max(255),portType,direction,medium,connectorType:z.string().max(64).nullable().optional(),status:z.enum(["AVAILABLE","CONNECTED","INACTIVE"]),description:z.string().max(5000).nullable().optional()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);try{return await inBranch(ctx,input.branchId,async tx=>{const before=await tx`SELECT name,port_type,direction,medium,connector_type,status,description,active FROM asset_ports WHERE id=${input.id}::uuid`;if(!before.length)throw new TRPCError({code:"NOT_FOUND",message:"Port was not found"});await tx`UPDATE asset_ports SET name=${input.name},port_type=${input.portType},direction=${input.direction},medium=${input.medium},connector_type=${input.connectorType??null},status=${input.status},description=${input.description??null},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid`;await audit(tx,ctx.pgTenant.tenantId,input.branchId,"PORT",input.id,"port_updated",ctx.pgTenant.externalSubject,{before:before[0]});return {id:input.id};});}catch(e){controlled(e);}}),
  setPortActive: pgProtectedProcedure.input(branchInput.extend({id:uuid,active:z.boolean()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);return inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE asset_ports SET active=${input.active},status=${input.active?"AVAILABLE":"INACTIVE"},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Port was not found"});await audit(tx,ctx.pgTenant.tenantId,input.branchId,"PORT",input.id,input.active?"port_activated":"port_deactivated",ctx.pgTenant.externalSubject);return {id:input.id};});}),
  listLinks: pgProtectedProcedure.input(branchInput.extend({assetId:uuid.optional(),systemSolutionId:uuid.optional()})).query(({ctx,input})=>inBranch(ctx,input.branchId,tx=>tx`SELECT l.id::text,l.code,l.name,l.link_type AS "linkType",l.endpoint_a_port_id::text AS "endpointAPortId",l.endpoint_b_port_id::text AS "endpointBPortId",l.status,l.medium,l.description,l.active,aa.asset_id::text AS "assetAId",ab.asset_id::text AS "assetBId" FROM asset_links l JOIN asset_ports aa ON aa.id=l.endpoint_a_port_id AND aa.tenant_id=l.tenant_id JOIN asset_ports ab ON ab.id=l.endpoint_b_port_id AND ab.tenant_id=l.tenant_id JOIN assets a ON a.id=aa.asset_id AND a.tenant_id=l.tenant_id JOIN assets b ON b.id=ab.asset_id AND b.tenant_id=l.tenant_id WHERE (${input.assetId??null}::uuid IS NULL OR aa.asset_id=${input.assetId??null}::uuid OR ab.asset_id=${input.assetId??null}::uuid) AND (${input.systemSolutionId??null}::uuid IS NULL OR a.system_solution_id=${input.systemSolutionId??null}::uuid OR b.system_solution_id=${input.systemSolutionId??null}::uuid) ORDER BY l.code`)),
  getLink: pgProtectedProcedure.input(branchInput.extend({id:uuid})).query(async({ctx,input})=>{const rows=await inBranch(ctx,input.branchId,tx=>tx`SELECT id::text,code,name,link_type AS "linkType",endpoint_a_port_id::text AS "endpointAPortId",endpoint_b_port_id::text AS "endpointBPortId",status,medium,description,active FROM asset_links WHERE id=${input.id}::uuid`);if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Link was not found"});return rows[0];}),
  createLink: pgProtectedProcedure.input(branchInput.extend({code:z.string().trim().min(1).max(64),name:z.string().trim().min(1).max(255),linkType,endpointAPortId:uuid,endpointBPortId:uuid,medium,description:z.string().max(5000).nullable().optional()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);try{return await inBranch(ctx,input.branchId,async tx=>{const id=randomUUID();await tx`INSERT INTO asset_links(id,tenant_id,branch_id,code,name,link_type,endpoint_a_port_id,endpoint_b_port_id,medium,description,created_by,updated_by) VALUES(${id}::uuid,${ctx.pgTenant.tenantId}::uuid,${input.branchId}::uuid,${input.code.toUpperCase()},${input.name},${input.linkType},${input.endpointAPortId}::uuid,${input.endpointBPortId}::uuid,${input.medium},${input.description??null},${ctx.pgTenant.externalSubject},${ctx.pgTenant.externalSubject})`;await audit(tx,ctx.pgTenant.tenantId,input.branchId,"LINK",id,"link_created",ctx.pgTenant.externalSubject);return{id};});}catch(e){controlled(e);}}),
  updateLink: pgProtectedProcedure.input(branchInput.extend({id:uuid,name:z.string().trim().min(1).max(255),status:z.enum(["PLANNED","INSTALLED","ACTIVE","DEGRADED","INACTIVE","DECOMMISSIONED"]),description:z.string().max(5000).nullable().optional()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);return inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE asset_links SET name=${input.name},status=${input.status},description=${input.description??null},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Link was not found"});await audit(tx,ctx.pgTenant.tenantId,input.branchId,"LINK",input.id,"link_updated",ctx.pgTenant.externalSubject);return{id:input.id};});}),
  setLinkActive: pgProtectedProcedure.input(branchInput.extend({id:uuid,active:z.boolean()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);return inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE asset_links SET active=${input.active},status=${input.active?"ACTIVE":"INACTIVE"},decommissioned_at=${input.active?null:new Date()},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Link was not found"});await audit(tx,ctx.pgTenant.tenantId,input.branchId,"LINK",input.id,input.active?"link_activated":"link_deactivated",ctx.pgTenant.externalSubject);return{id:input.id};});}),
  listRelationships: pgProtectedProcedure.input(branchInput.extend({assetId:uuid})).query(({ctx,input})=>inBranch(ctx,input.branchId,tx=>tx`SELECT id::text,source_asset_id::text AS "sourceAssetId",target_asset_id::text AS "targetAssetId",relationship_type AS "relationshipType",status,description,active,source_system_solution_id::text AS "sourceSystemSolutionId",target_system_solution_id::text AS "targetSystemSolutionId" FROM asset_relationships WHERE source_asset_id=${input.assetId}::uuid OR target_asset_id=${input.assetId}::uuid ORDER BY created_at DESC`)),
  getRelationship: pgProtectedProcedure.input(branchInput.extend({id:uuid})).query(async({ctx,input})=>{const rows=await inBranch(ctx,input.branchId,tx=>tx`SELECT id::text,source_asset_id::text AS "sourceAssetId",target_asset_id::text AS "targetAssetId",relationship_type AS "relationshipType",status,description,active FROM asset_relationships WHERE id=${input.id}::uuid`);if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Relationship was not found"});return rows[0];}),
  createRelationship: pgProtectedProcedure.input(branchInput.extend({sourceAssetId:uuid,targetAssetId:uuid,relationshipType,description:z.string().max(5000).nullable().optional()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);try{return await inBranch(ctx,input.branchId,async tx=>{const id=randomUUID();await tx`INSERT INTO asset_relationships(id,tenant_id,branch_id,source_asset_id,target_asset_id,relationship_type,description,created_by,updated_by) VALUES(${id}::uuid,${ctx.pgTenant.tenantId}::uuid,${input.branchId}::uuid,${input.sourceAssetId}::uuid,${input.targetAssetId}::uuid,${input.relationshipType},${input.description??null},${ctx.pgTenant.externalSubject},${ctx.pgTenant.externalSubject})`;await audit(tx,ctx.pgTenant.tenantId,input.branchId,"RELATIONSHIP",id,"relationship_created",ctx.pgTenant.externalSubject);return{id};});}catch(e){controlled(e);}}),
  updateRelationship: pgProtectedProcedure.input(branchInput.extend({id:uuid,status:z.enum(["PLANNED","ACTIVE","INACTIVE","DECOMMISSIONED"]),description:z.string().max(5000).nullable().optional()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);return inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE asset_relationships SET status=${input.status},description=${input.description??null},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Relationship was not found"});await audit(tx,ctx.pgTenant.tenantId,input.branchId,"RELATIONSHIP",input.id,"relationship_updated",ctx.pgTenant.externalSubject);return{id:input.id};});}),
  setRelationshipActive: pgProtectedProcedure.input(branchInput.extend({id:uuid,active:z.boolean()})).mutation(async({ctx,input})=>{requireAdmin(ctx.pgTenant.tenantRole);return inBranch(ctx,input.branchId,async tx=>{const rows=await tx`UPDATE asset_relationships SET active=${input.active},status=${input.active?"ACTIVE":"INACTIVE"},updated_by=${ctx.pgTenant.externalSubject} WHERE id=${input.id}::uuid RETURNING id`;if(!rows.length)throw new TRPCError({code:"NOT_FOUND",message:"Relationship was not found"});await audit(tx,ctx.pgTenant.tenantId,input.branchId,"RELATIONSHIP",input.id,input.active?"relationship_activated":"relationship_deactivated",ctx.pgTenant.externalSubject);return{id:input.id};});}),
});
