CREATE TABLE `cctv_cameras` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idCamera` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`familia` varchar(100),
	`resolucion` varchar(50),
	`tipo` enum('bala','domo','ptz','fisheye','panoramica','otro') DEFAULT 'domo',
	`poe` boolean DEFAULT false,
	`area` varchar(255),
	`edificio` varchar(255),
	`ip` varchar(45),
	`mascara` varchar(45),
	`gateway` varchar(45),
	`mac` varchar(30),
	`internet` boolean DEFAULT false,
	`conexion` varchar(100),
	`switchId` int,
	`puertoSw` varchar(20),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`po` varchar(100),
	`tiempoUso` varchar(50),
	`garantiaExpiracion` date,
	`status` enum('active','inactive','maintenance','retired') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_cameras_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_idfs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idIdf` varchar(100),
	`nombre` varchar(255),
	`ubicacion` varchar(255),
	`tipo` enum('IDF','MDF','gabinete') NOT NULL DEFAULT 'IDF',
	`numeroRacks` int,
	`numGabinetes` int,
	`capacidadRacks` int,
	`capacidadGabinetes` int,
	`fibraOptica` boolean DEFAULT false,
	`tipoFibra` varchar(100),
	`idfCompartido` boolean DEFAULT false,
	`compartidoCon` varchar(255),
	`noSwitches` int,
	`noServidores` int,
	`noUps` int,
	`refrigerado` boolean DEFAULT false,
	`controlAcceso` boolean DEFAULT false,
	`tipoControlAcceso` varchar(100),
	`comentarios` text,
	`observaciones` text,
	`fotoUrl` text,
	`status` enum('active','inactive','maintenance') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_idfs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_licenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idLicencia` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`tipo` enum('perpetua','suscripcion','trial','otro') NOT NULL DEFAULT 'suscripcion',
	`noContrato` varchar(100),
	`fechaInicio` date,
	`fechaExpiracion` date,
	`equipoAsignado` varchar(255),
	`ubicacion` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`ordenCompra` varchar(100),
	`tiempoUso` varchar(50),
	`otro` text,
	`expirado` boolean DEFAULT false,
	`status` enum('active','expired','cancelled','pending_renewal') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_licenses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_monitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idMonitor` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('monitor','pantalla','videowall','otro') NOT NULL DEFAULT 'monitor',
	`tamano` varchar(20),
	`resolucion` enum('HD 720p','Full HD 1K','QHD 2K','UHD 4K','8K','otro') DEFAULT 'Full HD 1K',
	`tecnologia` enum('LED','QLED','OLED','LCD','IPS','otro') DEFAULT 'LED',
	`puerto` enum('HDMI','VGA','DVI','DisplayPort','USB-C','otro') DEFAULT 'HDMI',
	`ubicacion` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`ordenCompra` varchar(100),
	`garantiaExpiracion` date,
	`tiempoUso` varchar(50),
	`ups` boolean DEFAULT false,
	`conexion` varchar(100),
	`status` enum('active','inactive','maintenance','retired') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_monitors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_servers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idServer` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('nvr','workstation','appliance','servidor','otro') NOT NULL DEFAULT 'nvr',
	`versionVms` varchar(100),
	`licencias` int,
	`licenciasLibres` int,
	`versionLic` varchar(100),
	`numCamaras` int,
	`so` varchar(100),
	`memoria` varchar(50),
	`procesador` varchar(100),
	`storage` varchar(100),
	`ip` varchar(45),
	`mascara` varchar(45),
	`gateway` varchar(45),
	`dns` varchar(45),
	`nic` varchar(50),
	`mac` varchar(30),
	`ubicacion` varchar(255),
	`usuario` varchar(100),
	`contrasena` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`ordenCompra` varchar(100),
	`garantiaExpiracion` date,
	`tiempoUso` varchar(50),
	`status` enum('active','inactive','maintenance','retired') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_servers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_switches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idfId` int,
	`idSwitch` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('poe','standard','appliance','core','acceso','otro') NOT NULL DEFAULT 'poe',
	`firmware` varchar(100),
	`puertos` int,
	`puertosPoe` int,
	`capacidadPto` varchar(50),
	`numCamaras` int,
	`puertosLibres` int,
	`ip` varchar(45),
	`ubicacion` varchar(255),
	`usuario` varchar(100),
	`contrasena` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`ordenCompra` varchar(100),
	`garantiaExpiracion` date,
	`tiempoUso` varchar(50),
	`status` enum('active','inactive','maintenance','retired') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_switches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cctv_ups` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idfId` int,
	`idUps` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('torre','rack','online','interactivo','otro') NOT NULL DEFAULT 'rack',
	`capacidad` varchar(50),
	`autonomia` varchar(50),
	`equiposConectados` int,
	`consumoActual` varchar(50),
	`tarjetaRed` boolean DEFAULT false,
	`ip` varchar(45),
	`ubicacion` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`ordenCompra` varchar(100),
	`garantiaExpiracion` date,
	`tiempoUso` varchar(50),
	`status` enum('active','inactive','maintenance','retired') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_ups_id` PRIMARY KEY(`id`)
);
