CREATE TABLE `cctv_maintenance_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('cameras','idfs','licenses','monitors','servers','switches','ups') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`type` enum('preventive','corrective','predictive','inspection','replacement','upgrade','other') NOT NULL DEFAULT 'preventive',
	`status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'completed',
	`title` varchar(255) NOT NULL,
	`description` text,
	`findings` text,
	`actions` text,
	`technician` varchar(255),
	`scheduledDate` date,
	`executedDate` date,
	`durationHours` decimal(5,2),
	`cost` decimal(12,2),
	`nextMaintenanceDate` date,
	`attachmentUrl` text,
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cctv_maintenance_log_id` PRIMARY KEY(`id`)
);
