CREATE TABLE `ac_controllers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idController` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('standalone','networked','cloud','otro') DEFAULT 'networked',
	`puertas` int DEFAULT 1,
	`ip` varchar(45),
	`mac` varchar(30),
	`firmware` varchar(100),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ac_controllers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ac_doors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idDoor` varchar(100),
	`nombre` varchar(255) NOT NULL,
	`tipo` enum('entrada','salida','bidireccional','emergencia','otro') DEFAULT 'bidireccional',
	`material` varchar(100),
	`cerradura` varchar(100),
	`area` varchar(255),
	`edificio` varchar(255),
	`controladoraId` int,
	`lectoresIds` text,
	`status` enum('active','inactive','maintenance','retired','damaged') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`amount` decimal(12,2),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ac_doors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ac_maintenance_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('readers','controllers','doors') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`type` enum('preventive','corrective','predictive','inspection','replacement','upgrade','other') NOT NULL DEFAULT 'preventive',
	`status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'completed',
	`title` varchar(255) NOT NULL,
	`description` text,
	`findings` text,
	`actions` text,
	`technician` varchar(255),
	`scheduledDate` date,
	`executedDate` date,
	`durationHours` decimal(5,2),
	`cost` decimal(12,2),
	`nextMaintenanceDate` date,
	`beforePhotoUrl` text,
	`beforePhotoKey` varchar(500),
	`afterPhotoUrl` text,
	`afterPhotoKey` varchar(500),
	`clientSignatureUrl` text,
	`clientSignatureKey` varchar(500),
	`clientName` varchar(255),
	`reportGenerated` boolean DEFAULT false,
	`policyId` int,
	`programId` int,
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ac_maintenance_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ac_maintenance_program_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`programId` int NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('readers','controllers','doors') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`itemLocation` varchar(255),
	`area` varchar(255),
	`requiresLift` boolean DEFAULT false,
	`noTechnicians` int DEFAULT 1,
	`observations` text,
	`sortOrder` int DEFAULT 0,
	`scheduledDays` varchar(50),
	`scheduledDates` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ac_maintenance_program_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ac_maintenance_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`policyId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`totalVisits` int NOT NULL,
	`completedVisits` int NOT NULL DEFAULT 0,
	`frequency` enum('monthly','bimonthly','quarterly','biannual','annual','custom') NOT NULL DEFAULT 'quarterly',
	`startDate` date NOT NULL,
	`endDate` date NOT NULL,
	`technician` varchar(255),
	`schedule` varchar(100),
	`visitWeekStart` date,
	`programMonth` varchar(20),
	`programYear` varchar(10),
	`status` enum('active','completed','cancelled') NOT NULL DEFAULT 'active',
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ac_maintenance_programs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ac_readers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idReader` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('hid','biometrico','tarjeta','pin','facial','rfid','otro') DEFAULT 'tarjeta',
	`tecnologia` varchar(100),
	`area` varchar(255),
	`edificio` varchar(255),
	`puerta` varchar(255),
	`ip` varchar(45),
	`mac` varchar(30),
	`controladoraId` int,
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ac_readers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_ducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idDuct` varchar(100),
	`tipo` enum('canaleta','bandeja','tuberia','charola','otro') DEFAULT 'canaleta',
	`material` varchar(100),
	`dimensiones` varchar(100),
	`longitud` decimal(8,2),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_ducts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_maintenance_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('switches','patch_panels','outlets','ducts') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`type` enum('preventive','corrective','predictive','inspection','replacement','upgrade','other') NOT NULL DEFAULT 'preventive',
	`status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'completed',
	`title` varchar(255) NOT NULL,
	`description` text,
	`findings` text,
	`actions` text,
	`technician` varchar(255),
	`scheduledDate` date,
	`executedDate` date,
	`durationHours` decimal(5,2),
	`cost` decimal(12,2),
	`nextMaintenanceDate` date,
	`beforePhotoUrl` text,
	`beforePhotoKey` varchar(500),
	`afterPhotoUrl` text,
	`afterPhotoKey` varchar(500),
	`clientSignatureUrl` text,
	`clientSignatureKey` varchar(500),
	`clientName` varchar(255),
	`reportGenerated` boolean DEFAULT false,
	`policyId` int,
	`programId` int,
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_maintenance_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_maintenance_program_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`programId` int NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('switches','patch_panels','outlets','ducts') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`itemLocation` varchar(255),
	`area` varchar(255),
	`requiresLift` boolean DEFAULT false,
	`noTechnicians` int DEFAULT 1,
	`observations` text,
	`sortOrder` int DEFAULT 0,
	`scheduledDays` varchar(50),
	`scheduledDates` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cabled_maintenance_program_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_maintenance_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`policyId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`totalVisits` int NOT NULL,
	`completedVisits` int NOT NULL DEFAULT 0,
	`frequency` enum('monthly','bimonthly','quarterly','biannual','annual','custom') NOT NULL DEFAULT 'quarterly',
	`startDate` date NOT NULL,
	`endDate` date NOT NULL,
	`technician` varchar(255),
	`schedule` varchar(100),
	`visitWeekStart` date,
	`programMonth` varchar(20),
	`programYear` varchar(10),
	`status` enum('active','completed','cancelled') NOT NULL DEFAULT 'active',
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_maintenance_programs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_outlets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idOutlet` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`puertos` int DEFAULT 2,
	`categoria` enum('cat5e','cat6','cat6a','cat7','fibra','otro') DEFAULT 'cat6',
	`area` varchar(255),
	`edificio` varchar(255),
	`patchPanelId` int,
	`puertoPanel` varchar(20),
	`switchId` int,
	`puertoSwitch` varchar(20),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_outlets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_patch_panels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idPanel` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`puertos` int DEFAULT 24,
	`categoria` enum('cat5e','cat6','cat6a','cat7','fibra','otro') DEFAULT 'cat6',
	`rack` varchar(100),
	`unidadRack` varchar(20),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_patch_panels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `cabled_switches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idSwitch` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('switch_l2','switch_l3','router','core','distribucion','acceso','otro') DEFAULT 'switch_l2',
	`puertos` int DEFAULT 24,
	`puertosPoE` int DEFAULT 0,
	`velocidad` varchar(50),
	`administrable` boolean DEFAULT true,
	`ip` varchar(45),
	`mac` varchar(30),
	`vlan` varchar(255),
	`firmware` varchar(100),
	`rack` varchar(100),
	`unidadRack` varchar(20),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `cabled_switches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_amplifiers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idAmplifier` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('monocanal','multicanal','matricial','ip','otro') DEFAULT 'monocanal',
	`potencia` varchar(50),
	`canales` int DEFAULT 1,
	`zonas` int DEFAULT 1,
	`ip` varchar(45),
	`rack` varchar(100),
	`unidadRack` varchar(20),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_amplifiers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_consoles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idConsole` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('microfono_paging','consola_ip','telefono_paging','panel_control','otro') DEFAULT 'microfono_paging',
	`zonas` int DEFAULT 1,
	`ip` varchar(45),
	`area` varchar(255),
	`edificio` varchar(255),
	`amplificadorId` int,
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_consoles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_maintenance_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('amplifiers','speakers','consoles','power_supplies') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`type` enum('preventive','corrective','predictive','inspection','replacement','upgrade','other') NOT NULL DEFAULT 'preventive',
	`status` enum('scheduled','in_progress','completed','cancelled') NOT NULL DEFAULT 'completed',
	`title` varchar(255) NOT NULL,
	`description` text,
	`findings` text,
	`actions` text,
	`technician` varchar(255),
	`scheduledDate` date,
	`executedDate` date,
	`durationHours` decimal(5,2),
	`cost` decimal(12,2),
	`nextMaintenanceDate` date,
	`beforePhotoUrl` text,
	`beforePhotoKey` varchar(500),
	`afterPhotoUrl` text,
	`afterPhotoKey` varchar(500),
	`clientSignatureUrl` text,
	`clientSignatureKey` varchar(500),
	`clientName` varchar(255),
	`reportGenerated` boolean DEFAULT false,
	`policyId` int,
	`programId` int,
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_maintenance_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_maintenance_program_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`programId` int NOT NULL,
	`tenantId` int NOT NULL,
	`category` enum('amplifiers','speakers','consoles','power_supplies') NOT NULL,
	`itemId` int NOT NULL,
	`itemName` varchar(255),
	`itemLocation` varchar(255),
	`area` varchar(255),
	`requiresLift` boolean DEFAULT false,
	`noTechnicians` int DEFAULT 1,
	`observations` text,
	`sortOrder` int DEFAULT 0,
	`scheduledDays` varchar(50),
	`scheduledDates` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `paging_maintenance_program_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_maintenance_programs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`policyId` int,
	`name` varchar(255) NOT NULL,
	`description` text,
	`totalVisits` int NOT NULL,
	`completedVisits` int NOT NULL DEFAULT 0,
	`frequency` enum('monthly','bimonthly','quarterly','biannual','annual','custom') NOT NULL DEFAULT 'quarterly',
	`startDate` date NOT NULL,
	`endDate` date NOT NULL,
	`technician` varchar(255),
	`schedule` varchar(100),
	`visitWeekStart` date,
	`programMonth` varchar(20),
	`programYear` varchar(10),
	`status` enum('active','completed','cancelled') NOT NULL DEFAULT 'active',
	`createdByUserId` int,
	`createdByUserName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_maintenance_programs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_power_supplies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idPower` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('ups','fuente_regulada','bateria_respaldo','otro') DEFAULT 'ups',
	`capacidad` varchar(50),
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_power_supplies_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `paging_speakers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`branchId` int,
	`idSpeaker` varchar(100),
	`marca` varchar(100),
	`modelo` varchar(100),
	`serie` varchar(100),
	`tipo` enum('techo','pared','columna','cuerno','subwoofer','otro') DEFAULT 'techo',
	`potencia` varchar(50),
	`impedancia` varchar(50),
	`zona` varchar(100),
	`amplificadorId` int,
	`area` varchar(255),
	`edificio` varchar(255),
	`proveedor` varchar(255),
	`fechaCompra` date,
	`garantiaExpiracion` date,
	`po` varchar(100),
	`invoiceNumber` varchar(100),
	`amount` decimal(12,2),
	`slaTier` varchar(10),
	`rfidTag` varchar(50),
	`status` enum('active','inactive','maintenance','retired','damaged','warranty') NOT NULL DEFAULT 'active',
	`observaciones` text,
	`fotoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `paging_speakers_id` PRIMARY KEY(`id`)
);
